### ISSUE TITLE
should we gitignore .vscode/.react/index.android.bundle ?

### ISSUE THREAD

**Issue by forki** [Krzysztof-Cieslak/fable-react_native-demo#1]

**Comment by forki** [comment]
in other words: the change in https://github.com/Krzysztof-Cieslak/fable-react_native-demo/commit/13ebf84000b8bc84a3cabdca415db27583a87a35 shows many autogenerated files. is that needed?

**Comment by Krzysztof-Cieslak** [comment]
Yeah, looks like `index.android.bundle ` should be ignored. Other changes in this commit looks good, I think.
