### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by scitesy** [Krzysztof-Cieslak/fable-react_native-demo#4]
Any idea on what I might be doing wrong?
I can't get past this error:
![screenshot_2016-07-28_12-11-48](https://cloud.githubusercontent.com/assets/45361/17220253/7d77da28-54bc-11e6-956b-b5b7135d3909.png)

**Comment by forki** [comment]
it's not ready yet. this is still private beta :-)

**Comment by forki** [comment]
are you trying to build latest bit from here?

**Comment by scitesy** [comment]
Yes. I'm trying to pull in the latest code as it changes. When reactnative hits the first line of the output javascript file it fails inside fable-core.  All I get are red screens so far:(
I wouldn't call it beta. Perhaps pre-alpha;) I was just hoping one of you had received this error overcame it and moved on.

**Comment by forki** [comment]
Please try the following:

Pull latest master 
git clean -xdf
npm install 
Open android simulator 
Open VS code 
Press F5
Press ctrl-shift-b

**Comment by scitesy** [comment]
Thanks. I'll try later today.

**Comment by forki** [comment]
Chris does it work for you?

**Comment by forki** [comment]
updated list with steps

**Comment by scitesy** [comment]
At step 6 after pressing F5, VS Code gives me "Error Configured debug type 'reactnative' is not supported."

**Comment by forki** [comment]
Do you have the react native plugin for VS code installed?

**Comment by forki** [comment]
#3 is fixed so step 7 is gone. I also added readme with install steps.

**Comment by scitesy** [comment]
Thank you for the guidance. I tested out the README. Everything seems to work from the VS Code side as it compile and then goes into debug mode. The emulator must not be set up correctly because it just sits with no response. Let me read more about the React plugin. Maybe I don't have the emulator set up in the way that the React plugin wants. I'll close this ticket. This is wonderful. Thanks for all of your efforts.

**Comment by forki** [comment]
android emulator is really frustrating.
I sometimes reboot and start from scratch because that stupid thing is in strange mode I have no idea how to fix it

**Comment by forki** [comment]
and now I have the same error message like you had above ;-(

**Comment by forki** [comment]
recompile seems to work. don't ask me why

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/17247642/e46d3452-5594-11e6-92de-afd68ea9cde2.png)

**Comment by forki** [comment]
![styles](https://cloud.githubusercontent.com/assets/57396/17361686/f3750cd2-5971-11e6-85c5-82b57a77d340.gif)

**Comment by scitesy** [comment]
That looks great!

**Comment by forki** [comment]
@scitesy can you please retry? #5 is a possible fix

**Comment by scitesy** [comment]
Yes this works now! I didn't do the building or running of the program through VSCode. For some reason the react-native VSCode plugin won't connect to my Android emulator. I did it from the command line and it works. The kicker? I'm on Linux too!

**Comment by scitesy** [comment]
![imagepickerhome](https://cloud.githubusercontent.com/assets/45361/17410921/d733592a-5a43-11e6-9291-9e4dd792acab.png)

**Comment by scitesy** [comment]
![selectimageoptions](https://cloud.githubusercontent.com/assets/45361/17410944/eb21449c-5a43-11e6-8d46-49cd305640a1.png)

**Comment by scitesy** [comment]
When I click Take Photo... I get a "Camera error Can't connect to the camera." dialog. I'm sure that has something to do with my setup though.

**Comment by Krzysztof-Cieslak** [comment]
Yeah, you need to turn camera on in emulator device settings.
